//
//  Settings+Keys.swift
//  Mlem
//
//  Created by Eric Andrews on 2025-04-07.
//

extension SettingsValues {
    enum CodingKeys: String, CodingKey {
        case _a11y_readPostIndicator = "a11y_readPostIndicator"
        case _a11y_readOutlineThickness = "a11y_readOutlineThickness"
        case _a11y_showSettingsIcons = "a11y_showSettingsIcons"
        case _a11y_websiteThumbnailIcon = "a11y_websiteThumbnailIcon"
        case _a11y_zoomSliderLocation = "a11y_zoomSliderLocation"
        case _accounts_defaultId = "accounts_defaultId"
        case _accounts_grouped = "accounts_grouped"
        case _accounts_sort = "accounts_sort"
        case _accounts_keepPlace = "accounts_keepPlace"
        case _appearance_interfaceStyle = "appearance_interfaceStyle"
        case _appearance_palette = "appearance_palette"
        case _markdown_wrapCodeBlockLines = "markdown_wrapCodeBlockLines"
        case _behavior_biometricUnlock = "behavior_biometricUnlock"
        case _behavior_confirmImageUploads = "behavior_confirmImageUploads"
        case _behavior_enableQuickSwipes = "behavior_enableQuickSwipes"
        case _behavior_hapticLevel = "behavior_hapticLevel"
        case _behavior_internetSpeed = "behavior_internetSpeed"
        case _behavior_upvoteOnSave = "behavior_upvoteOnSave"
        case _behavior_autoplayMedia = "behavior_autoplayMedia"
        case _behavior_muteVideos = "behavior_muteVideos"
        case _behavior_infiniteScroll = "behavior_infiniteScroll"
        case _comment_behaviors_collapseChildren = "comment_behaviors_collapseChildren"
        case _comment_compact = "comment_compact"
        case _comment_defaultSort = "comment_defaultSort"
        case _comment_gestures_tapToCollapse = "comment_gestures_tapToCollapse"
        case _comment_jumpButton = "comment_jumpButton"
        case _comment_showCreatorInstance = "comment_showCreatorInstance"
        case _comment_maxDepth = "comment_maxDepth"
        case _community_showAvatar = "community_showAvatar"
        case _community_showBanner = "community_showBanner"
        case _community_showInstance = "community_showInstance"
        case _dev_developerMode = "dev_developerMode"
        case _feed_default = "feed_default"
        case _feed_markReadOnScroll = "feed_markReadOnScroll"
        case _feed_showRead = "feed_showRead"
        case _inbox_showRead = "inbox_showRead"
        case _links_displayMode = "links_displayMode"
        case _links_openInBrowser = "links_openInBrowser"
        case _links_readerMode = "links_readerMode"
        case _links_shareMode = "links_shareMode"
        case _links_embedLoops = "links_embedLoops"
        case _media_animatedAvatars = "media_animatedAvatars"
        case _menus_allModActions = "menus_allModActions"
        case _menus_modActionGrouping = "menus_modActionGrouping"
        case _post_defaultSort = "post_defaultSort"
        case _post_fallbackSort = "post_fallbackSort"
        case _post_limitImageHeight = "post_limitImageHeight"
        case _post_showCreator = "post_showCreator"
        case _post_showCreatorInstance = "post_showCreatorInstance"
        case _post_showSubscribedStatus = "post_showSubscribedStatus"
        case _post_showWebsitePreview = "post_showWebsitePreview"
        case _post_size = "post_size"
        case _post_allowMultipleColumns = "post_allowMultipleColumns"
        case _post_thumbnailLocation = "post_thumbnailLocation"
        case _post_webPreview_showHost = "post_webPreview_showHost"
        case _post_webPreview_showIcon = "post_webPreview_showIcon"
        case _post_showDownvotesCompact = "post_showDownvotesCompact"
        case _post_gestures_tapToCollapse = "post_gestures_tapToCollapse"
        case _profile_showBanner = "profile_showBanner"
        case _privacy_autoBypassImageProxy = "privacy_autoBypassImageProxy"
        case _privacy_showFavicons = "privacy_showFavicons"
        case _safety_blurNsfw = "safety_blurNsfw"
        case _safety_enableModlogWarning = "safety_enableModlogWarning"
        case _safety_enableNsfwCommunityWarning = "safety_enableNsfwCommunityWarning"
        case _tab_gestures_enableLongPress = "tab_gestures_enableLongPress"
        case _tab_gestures_enableSwipeUp = "tab_gestures_enableSwipeUp"
        case _tab_profile_labelType = "tab_profile_labelType"
        case _tab_profile_showAvatar = "tab_profile_showAvatar"
        case _tab_inbox_badgeIncludedTypes = "tab_inbox_badgeIncludedTypes"
        case _tab_showNames = "tab_showNames"
        case _tip_feedWelcomePrompt = "tip_feedWelcomePrompt"
        case _person_showAvatar = "person_showAvatar"
        case _person_showInstance = "person_showInstance"
        case _status_bypassImageProxyShown = "status_bypassImageProxyShown"
        case _subscriptions_instanceLocation = "subscriptions_instanceLocation"
        case _subscriptions_sort = "subscriptions_sort"
        case _navigation_sidebarVisibleByDefault = "navigation_sidebarVisibleByDefault"
        case _navigation_swipeAnywhere = "navigation_swipeAnywhere"
        case _filters_keywordFilterEnabled = "filters_keywordFilterEnabled"
        case _interactionBar_alternateReportLayout = "interactionBar_alternateReportLayout"
     
        case inbox_badge_includeApplications = "inbox_badge_includeApplications"
        case inbox_badge_includeMessageReports = "inbox_badge_includeMessageReports"
        case inbox_badge_includeMod = "inbox_badge_includeMod"
        case inbox_badge_includePersonal = "inbox_badge_includePersonal"
    }
}
