// 
//  MockErrorHandler.swift
//  MlemTests
//
//  Created by mormaer on 06/08/2023.
//  
//

@testable import Mlem

import Foundation

/// An object which can be used under test to receive errors as they are generated by the application
///  - Note: Use this by supplying it as the test depedency where required, eg
///  ```
///  someObject = withDependencies {
///      $0.errorHandler = MockErrorHandler { /* receive error */ }
///  } operation: {
///      someObject()
///  }
///  ```
class MockErrorHandler: ErrorHandler {
    
    var didReceiveError: (Error) -> Void
    
    init(didReceiveError: @escaping (Error) -> Void) {
        self.didReceiveError = didReceiveError
    }
    
    override func handle(
        _ error: ContextualError?,
        file: StaticString = #fileID,
        function: StaticString = #function,
        line: Int = #line
    ) {
        if let error {
            didReceiveError(error)
        }
    }
}
