name: xcodebuild

inputs:
  xcode_version: 
    required: true
  xcodebuild_destination:
    required: true
  xcodebuild_action:
    required: true

runs:
  using: "composite"
  steps:
  - uses: maxim-lobanov/setup-xcode@v1
    name: Set Xcode Version
    with:
      xcode-version: "${{ inputs.xcode_version }}"

  - name: "Test SDK versions"
    shell: bash
    run: |
      xcodebuild -showsdks

  - name: "Xcode Build"
    uses: sersoft-gmbh/xcodebuild-action@v3
    with:
      project: Mlem.xcodeproj
      scheme: Mlem
      destination: "${{ inputs.xcodebuild_destination }}"
      action: "${{ inputs.xcodebuild_action }}"
      result-bundle-path: build_results.xcresult
