name: Improvement Proposal
description: Propose an improvement for Mlem.
type: "Feature"

body:
- type: checkboxes
  attributes:
    label: Requirements
    description: Before you create this issue, please check the following.
    options:
    - label: There are no existing issues for this feature.
      required: true
    - label: This is a request for a **single** feature (create multiple issues for multiple feature requests).
      required: true
- type: textarea
  attributes:
    label: "Description"
    description: "Please describe how you would like Mlem to be improved."
