name: CI - Lint

on:
    # Run in master as CI
    push:
        branches:
        - master
        
    pull_request:
        branches:
        - master
        - dev

    # Run when we tweak Swift or supporting files
#    pull_request:
#        paths:
#        - '.github/workflows/swiftlint.yml'
#        - '.swiftlint.yml'
#        - '**/*.swift'
#        - 'Mlem.xcodeproj/project.pbxproj'

- uses: dorny/paths-filter@v4
  id: changes
  with:
    filters: |
      src:
        - '.github/workflows/swiftlint.yml'
        - '.swiftlint.yml'
        - '**/*.swift'
        - 'Mlem.xcodeproj/project.pbxproj'

jobs:
  SwiftLint:
    if: steps.changes.outputs.src == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
            args: --strict
