//
//  App Constants.swift
//  Mlem
//
//  Created by David Bureš on 03.05.2023.
//

import Foundation

struct AppConstants
{
    static let webSocketSession: URLSession = URLSession(configuration: .default)
    
    static let demoPostResponse: String = """
{
    "op": "GetPosts",
    "data": {
        "posts": [
            {
                "id": 265082,
                "name": "Check out these Soviet high rises",
                "url": "https://www.hexbear.net/pictrs/image/LQeqg8Tqzy.jpg",
                "body": null,
                "creator_id": 1790,
                "community_id": 41,
                "removed": false,
                "locked": false,
                "published": "2023-05-03T17:45:45.848491",
                "updated": null,
                "deleted": false,
                "nsfw": false,
                "stickied": false,
                "featured": false,
                "embed_title": null,
                "embed_description": null,
                "embed_html": "<img src=\\"https://www.hexbear.net/pictrs/image/LQeqg8Tqzy.jpg\\">",
                "thumbnail_url": "https://www.hexbear.net/pictrs/image/IP9FxaXtdK.jpg",
                "ap_id": "https://www.hexbear.net/post/265082",
                "local": true,
                "creator_actor_id": "https://www.hexbear.net/u/HarryLime",
                "creator_local": true,
                "creator_name": "HarryLime",
                "creator_preferred_username": null,
                "creator_published": "2020-07-27T20:41:48.003527",
                "creator_avatar": null,
                "creator_tags": {
                    "pronouns": "any"
                },
                "creator_community_tags": null,
                "banned": false,
                "banned_from_community": false,
                "community_actor_id": "https://www.hexbear.net/c/urbanism",
                "community_local": true,
                "community_name": "urbanism",
                "community_icon": null,
                "community_removed": false,
                "community_deleted": false,
                "community_nsfw": false,
                "community_hide_from_all": false,
                "number_of_comments": 1,
                "score": 8,
                "upvotes": 8,
                "downvotes": 0,
                "hot_rank": 2308,
                "hot_rank_active": 2895,
                "newest_activity_time": "2023-05-03T18:01:06.101529",
                "user_id": null,
                "my_vote": null,
                "subscribed": null,
                "read": null,
                "saved": null
            },
            {
                "id": 265075,
                "name": "Goop consumer neoliberals are like \\"If you notice a pungent smell after mixing household cleaners, that's just the spiritual toxins leaving your home\\"",
                "url": null,
                "body": "you thought the ivermectin covid people were crazy, these petite bourgeois white women are literally doing World War one chemical weapons against themselves. \\"if it feels like shit it must be healthy, that means the ~~bloodletting~~ vomit and diarrhea treatment is working!\\"\\n",
                "creator_id": 24233,
                "community_id": 73,
                "removed": false,
                "locked": false,
                "published": "2023-05-03T17:16:40.168743",
                "updated": null,
                "deleted": false,
                "nsfw": false,
                "stickied": false,
                "featured": false,
                "embed_title": null,
                "embed_description": null,
                "embed_html": null,
                "thumbnail_url": null,
                "ap_id": "https://www.hexbear.net/post/265075",
                "local": true,
                "creator_actor_id": "https://www.hexbear.net/u/gardenSkink",
                "creator_local": true,
                "creator_name": "gardenSkink",
                "creator_preferred_username": null,
                "creator_published": "2023-01-23T08:33:02.894631",
                "creator_avatar": null,
                "creator_tags": {
                    "pronouns": "none/use name"
                },
                "creator_community_tags": null,
                "banned": false,
                "banned_from_community": false,
                "community_actor_id": "https://www.hexbear.net/c/chapotraphouse",
                "community_local": true,
                "community_name": "chapotraphouse",
                "community_icon": null,
                "community_removed": false,
                "community_deleted": false,
                "community_nsfw": false,
                "community_hide_from_all": false,
                "number_of_comments": 6,
                "score": 23,
                "upvotes": 23,
                "downvotes": 0,
                "hot_rank": 2301,
                "hot_rank_active": 3781,
                "newest_activity_time": "2023-05-03T17:54:59.577427",
                "user_id": null,
                "my_vote": null,
                "subscribed": null,
                "read": null,
                "saved": null
            },
            {
                "id": 265076,
                "name": "the Jeffrey Epstein/Eyes Wide Shut PMC class is literally unable to differentiate sounds of anguished human expression from sounds of orgasms",
                "url": "https://www.nme.com/news/music/concert-goer-has-loud-and-full-body-orgasm-during-la-philharmonic-performance-3437928",
                "body": ">Concert-goer has “loud and full body orgasm” during LA Philharmonic performance. The orchestra \\"politely carried on\\"\\n\\n>The incident happened while the orchestra was performing Tchaikovsky’s Symphony No. 5. “A woman in the audience had [a] loud and full body orgasm during the 5th’s second movement,” tweeted Magnus Fiennes, a composer and music producer who was in attendance. “Band politely carried on. Props to LAPhil (and Pytor Ilyich) for bringing it on.”\\n\\n>In a reply to Fiennes’ tweet, however, someone else who was in attendance suggested the moan could have been something quite different. “I was there. This is not what happened. The poor woman had a breakdown of some sort,” he replied. “Speaking to Elim after the concert (we are friends since out time together at U of M) and we were all worried it was a medical emergency. Please have more respect.”\\n\\nwait, you mean the class of people doing weird pagan/satanic temple rituals of human sacrifice like in that Stanley Kubrick movie can't tell joy apart from happiness? So weird!  :will-fancy: :agony:",
                "creator_id": 24233,
                "community_id": 6,
                "removed": false,
                "locked": false,
                "published": "2023-05-03T17:20:11.206856",
                "updated": "2023-05-03T17:20:24.410098",
                "deleted": false,
                "nsfw": false,
                "stickied": false,
                "featured": false,
                "embed_title": "Woman has \\"loud and full body orgasm\\" during classical concert",
                "embed_description": "The LA Philharmonic Orchestra were playing a Tchaikovsky symphony",
                "embed_html": null,
                "thumbnail_url": "https://www.hexbear.net/pictrs/image/SfDWpN46ke.jpg",
                "ap_id": "https://www.hexbear.net/post/265076",
                "local": true,
                "creator_actor_id": "https://www.hexbear.net/u/gardenSkink",
                "creator_local": true,
                "creator_name": "gardenSkink",
                "creator_preferred_username": null,
                "creator_published": "2023-01-23T08:33:02.894631",
                "creator_avatar": null,
                "creator_tags": {
                    "pronouns": "none/use name"
                },
                "creator_community_tags": null,
                "banned": false,
                "banned_from_community": false,
                "community_actor_id": "https://www.hexbear.net/c/news",
                "community_local": true,
                "community_name": "news",
                "community_icon": null,
                "community_removed": false,
                "community_deleted": false,
                "community_nsfw": false,
                "community_hide_from_all": false,
                "number_of_comments": 5,
                "score": 20,
                "upvotes": 20,
                "downvotes": 0,
                "hot_rank": 2270,
                "hot_rank_active": 3653,
                "newest_activity_time": "2023-05-03T17:56:18.704019",
                "user_id": null,
                "my_vote": null,
                "subscribed": null,
                "read": null,
                "saved": null
            },
            {
                "id": 265074,
                "name": "Drive (2011)",
                "url": "https://i.imgur.com/YUNzTI7.jpeg",
                "body": null,
                "creator_id": 22322,
                "community_id": 59,
                "removed": false,
                "locked": false,
                "published": "2023-05-03T17:14:15.746132",
                "updated": null,
                "deleted": false,
                "nsfw": false,
                "stickied": false,
                "featured": false,
                "embed_title": null,
                "embed_description": null,
                "embed_html": "<img src=\\"https://i.imgur.com/YUNzTI7.jpeg\\">",
                "thumbnail_url": "https://www.hexbear.net/pictrs/image/veALThdnhr.jpg",
                "ap_id": "https://www.hexbear.net/post/265074",
                "local": true,
                "creator_actor_id": "https://www.hexbear.net/u/jimmyjohnsandwich2",
                "creator_local": true,
                "creator_name": "jimmyjohnsandwich2",
                "creator_preferred_username": null,
                "creator_published": "2022-07-04T09:33:44.920679",
                "creator_avatar": null,
                "creator_tags": {
                    "pronouns": "any,they/them"
                },
                "creator_community_tags": null,
                "banned": false,
                "banned_from_community": false,
                "community_actor_id": "https://www.hexbear.net/c/memes",
                "community_local": true,
                "community_name": "memes",
                "community_icon": null,
                "community_removed": false,
                "community_deleted": false,
                "community_nsfw": false,
                "community_hide_from_all": false,
                "number_of_comments": 4,
                "score": 19,
                "upvotes": 19,
                "downvotes": 0,
                "hot_rank": 2127,
                "hot_rank_active": 3805,
                "newest_activity_time": "2023-05-03T17:58:54.962746",
                "user_id": null,
                "my_vote": null,
                "subscribed": null,
                "read": null,
                "saved": null
            },
            {
                "id": 265081,
                "name": "The DUNE-trix",
                "url": "https://www.hexbear.net/pictrs/image/ufVJMI7w2A.jpg",
                "body": "I just threw a few saturation and color filters to the max. \\nThis makes me worth $1 Billion. \\n\\nIt's like that whole banana duct taped to a wall stuff. :banana-duck-peeled:  that's how I see Dune. It isn't brilliant. It offends me. So I guess that's art. ",
                "creator_id": 23728,
                "community_id": 59,
                "removed": false,
                "locked": false,
                "published": "2023-05-03T17:45:09.486617",
                "updated": "2023-05-03T17:46:01.836359",
                "deleted": false,
                "nsfw": false,
                "stickied": false,
                "featured": false,
                "embed_title": null,
                "embed_description": null,
                "embed_html": "<img src=\\"https://www.hexbear.net/pictrs/image/ufVJMI7w2A.jpg\\">",
                "thumbnail_url": "https://www.hexbear.net/pictrs/image/e0CLYjKwPE.jpg",
                "ap_id": "https://www.hexbear.net/post/265081",
                "local": true,
                "creator_actor_id": "https://www.hexbear.net/u/Evilphd666",
                "creator_local": true,
                "creator_name": "Evilphd666",
                "creator_preferred_username": null,
                "creator_published": "2022-11-24T04:53:34.579536",
                "creator_avatar": null,
                "creator_tags": {
                    "pronouns": "he/him,comrade/them"
                },
                "creator_community_tags": null,
                "banned": false,
                "banned_from_community": false,
                "community_actor_id": "https://www.hexbear.net/c/memes",
                "community_local": true,
                "community_name": "memes",
                "community_icon": null,
                "community_removed": false,
                "community_deleted": false,
                "community_nsfw": false,
                "community_hide_from_all": false,
                "number_of_comments": 2,
                "score": 6,
                "upvotes": 6,
                "downvotes": 0,
                "hot_rank": 2068,
                "hot_rank_active": 2598,
                "newest_activity_time": "2023-05-03T18:00:40.404180",
                "user_id": null,
                "my_vote": null,
                "subscribed": null,
                "read": null,
                "saved": null
            },
            {
                "id": 265063,
                "name": "New gender just dropped",
                "url": "https://www.hexbear.net/pictrs/image/TsTCgYt4mx.png",
                "body": null,
                "creator_id": 24660,
                "community_id": 59,
                "removed": false,
                "locked": false,
                "published": "2023-05-03T16:33:03.564343",
                "updated": null,
                "deleted": false,
                "nsfw": false,
                "stickied": false,
                "featured": false,
                "embed_title": null,
                "embed_description": null,
                "embed_html": "<img src=\\"https://www.hexbear.net/pictrs/image/TsTCgYt4mx.png\\">",
                "thumbnail_url": "https://www.hexbear.net/pictrs/image/Uj2sUbeOxU.png",
                "ap_id": "https://www.hexbear.net/post/265063",
                "local": true,
                "creator_actor_id": "https://www.hexbear.net/u/Vladimir_Lentil",
                "creator_local": true,
                "creator_name": "Vladimir_Lentil",
                "creator_preferred_username": null,
                "creator_published": "2023-03-31T15:37:34.179304",
                "creator_avatar": null,
                "creator_tags": {
                    "pronouns": "she/her"
                },
                "creator_community_tags": null,
                "banned": false,
                "banned_from_community": false,
                "community_actor_id": "https://www.hexbear.net/c/memes",
                "community_local": true,
                "community_name": "memes",
                "community_icon": null,
                "community_removed": false,
                "community_deleted": false,
                "community_nsfw": false,
                "community_hide_from_all": false,
                "number_of_comments": 11,
                "score": 48,
                "upvotes": 48,
                "downvotes": 0,
                "hot_rank": 1819,
                "hot_rank_active": 4545,
                "newest_activity_time": "2023-05-03T17:54:31.439308",
                "user_id": null,
                "my_vote": null,
                "subscribed": null,
                "read": null,
                "saved": null
            },
            {
                "id": 265080,
                "name": "(UK) Government’s fast-tracking of new anti-protest laws days before coronation fuels anger and dismay",
                "url": "https://leftfootforward.org/2023/05/governments-fast-tracking-of-new-anti-protest-laws-days-before-coronation-fuels-anger-and-dismay/",
                "body": null,
                "creator_id": 6251,
                "community_id": 6,
                "removed": false,
                "locked": false,
                "published": "2023-05-03T17:39:34.112437",
                "updated": null,
                "deleted": false,
                "nsfw": false,
                "stickied": false,
                "featured": false,
                "embed_title": "Government’s fast-tracking of new anti-protest laws days before coronation fuels anger and dismay",
                "embed_description": "The Home Office claims the timing of the new powers is coincidental.",
                "embed_html": null,
                "thumbnail_url": "https://www.hexbear.net/pictrs/image/8YJEnrWghT.jpg",
                "ap_id": "https://www.hexbear.net/post/265080",
                "local": true,
                "creator_actor_id": "https://www.hexbear.net/u/DivineChaos100",
                "creator_local": true,
                "creator_name": "DivineChaos100",
                "creator_preferred_username": null,
                "creator_published": "2020-08-13T14:28:56.301338",
                "creator_avatar": null,
                "creator_tags": {
                    "pronouns": "none/use name"
                },
                "creator_community_tags": null,
                "banned": false,
                "banned_from_community": false,
                "community_actor_id": "https://www.hexbear.net/c/news",
                "community_local": true,
                "community_name": "news",
                "community_icon": null,
                "community_removed": false,
                "community_deleted": false,
                "community_nsfw": false,
                "community_hide_from_all": false,
                "number_of_comments": 1,
                "score": 5,
                "upvotes": 5,
                "downvotes": 0,
                "hot_rank": 1800,
                "hot_rank_active": 1826,
                "newest_activity_time": "2023-05-03T17:40:38.372200",
                "user_id": null,
                "my_vote": null,
                "subscribed": null,
                "read": null,
                "saved": null
            },
            {
                "id": 265067,
                "name": "Whereever I look I see him",
                "url": "https://www.hexbear.net/pictrs/image/jiZkmn5gmq.png",
                "body": null,
                "creator_id": 7334,
                "community_id": 73,
                "removed": false,
                "locked": false,
                "published": "2023-05-03T16:48:19.609724",
                "updated": null,
                "deleted": false,
                "nsfw": false,
                "stickied": false,
                "featured": false,
                "embed_title": null,
                "embed_description": null,
                "embed_html": "<img src=\\"https://www.hexbear.net/pictrs/image/jiZkmn5gmq.png\\">",
                "thumbnail_url": "https://www.hexbear.net/pictrs/image/6KlHJYczKd.png",
                "ap_id": "https://www.hexbear.net/post/265067",
                "local": true,
                "creator_actor_id": "https://www.hexbear.net/u/LegaliiizeIt",
                "creator_local": true,
                "creator_name": "LegaliiizeIt",
                "creator_preferred_username": null,
                "creator_published": "2020-08-21T09:43:20.795893",
                "creator_avatar": null,
                "creator_tags": {
                    "pronouns": "any,they/them"
                },
                "creator_community_tags": null,
                "banned": false,
                "banned_from_community": false,
                "community_actor_id": "https://www.hexbear.net/c/chapotraphouse",
                "community_local": true,
                "community_name": "chapotraphouse",
                "community_icon": null,
                "community_removed": false,
                "community_deleted": false,
                "community_nsfw": false,
                "community_hide_from_all": false,
                "number_of_comments": 2,
                "score": 26,
                "upvotes": 26,
                "downvotes": 0,
                "hot_rank": 1749,
                "hot_rank_active": 4200,
                "newest_activity_time": "2023-05-03T18:01:02.972587",
                "user_id": null,
                "my_vote": null,
                "subscribed": null,
                "read": null,
                "saved": null
            },
            {
                "id": 265087,
                "name": "Russian BMP-2 IFV, along with infantry squad",
                "url": "https://www.hexbear.net/pictrs/image/gS1qutcKxG.jpg",
                "body": null,
                "creator_id": 1619,
                "community_id": 30,
                "removed": false,
                "locked": false,
                "published": "2023-05-03T18:01:13.753440",
                "updated": "2023-05-03T18:01:31.371370",
                "deleted": false,
                "nsfw": false,
                "stickied": false,
                "featured": false,
                "embed_title": null,
                "embed_description": null,
                "embed_html": "<img src=\\"https://www.hexbear.net/pictrs/image/gS1qutcKxG.jpg\\">",
                "thumbnail_url": "https://www.hexbear.net/pictrs/image/xLj9FSlGKF.jpg",
                "ap_id": "https://www.hexbear.net/post/265087",
                "local": true,
                "creator_actor_id": "https://www.hexbear.net/u/Tervell",
                "creator_local": true,
                "creator_name": "Tervell",
                "creator_preferred_username": null,
                "creator_published": "2020-07-27T07:31:54.662674",
                "creator_avatar": null,
                "creator_tags": {
                    "pronouns": "he/him"
                },
                "creator_community_tags": null,
                "banned": false,
                "banned_from_community": false,
                "community_actor_id": "https://www.hexbear.net/c/guns",
                "community_local": true,
                "community_name": "guns",
                "community_icon": null,
                "community_removed": false,
                "community_deleted": false,
                "community_nsfw": false,
                "community_hide_from_all": false,
                "number_of_comments": 0,
                "score": 4,
                "upvotes": 4,
                "downvotes": 0,
                "hot_rank": 1721,
                "hot_rank_active": 1721,
                "newest_activity_time": "2023-05-03T18:01:13.753440",
                "user_id": null,
                "my_vote": null,
                "subscribed": null,
                "read": null,
                "saved": null
            },
            {
                "id": 265070,
                "name": "Even in an alternate Game Boy Color timeline, Snake is based",
                "url": "https://www.hexbear.net/pictrs/image/EKC4k2Onox.jpg",
                "body": "In this game, instead of taking on Foxhound on Shadow Moses, Snake is apparently sent to prevent an African militia called GLF from getting a Metal Gear\\n\\nIs it pronounced Gilf :thinking-about-it:  \\n",
                "creator_id": 23925,
                "community_id": 12,
                "removed": false,
                "locked": false,
                "published": "2023-05-03T16:58:09.311533",
                "updated": "2023-05-03T17:03:13.627864",
                "deleted": false,
                "nsfw": false,
                "stickied": false,
                "featured": false,
                "embed_title": null,
                "embed_description": null,
                "embed_html": "<img src=\\"https://www.hexbear.net/pictrs/image/EKC4k2Onox.jpg\\">",
                "thumbnail_url": "https://www.hexbear.net/pictrs/image/VQjppmQV5o.jpg",
                "ap_id": "https://www.hexbear.net/post/265070",
                "local": true,
                "creator_actor_id": "https://www.hexbear.net/u/TheronGuard",
                "creator_local": true,
                "creator_name": "TheronGuard",
                "creator_preferred_username": null,
                "creator_published": "2022-12-19T06:32:15.106624",
                "creator_avatar": null,
                "creator_tags": {
                    "pronouns": "he/him"
                },
                "creator_community_tags": null,
                "banned": false,
                "banned_from_community": false,
                "community_actor_id": "https://www.hexbear.net/c/games",
                "community_local": true,
                "community_name": "games",
                "community_icon": null,
                "community_removed": false,
                "community_deleted": false,
                "community_nsfw": false,
                "community_hide_from_all": false,
                "number_of_comments": 0,
                "score": 15,
                "upvotes": 15,
                "downvotes": 0,
                "hot_rank": 1685,
                "hot_rank_active": 1685,
                "newest_activity_time": "2023-05-03T16:58:09.311533",
                "user_id": null,
                "my_vote": null,
                "subscribed": null,
                "read": null,
                "saved": null
            }
        ]
    }
}
"""
}
